namespace CMS.PortalEngine.Web.UI
{
    /// <summary>
    /// Result class generated by <see cref="WebPartCodeGenerator"/>.
    /// </summary>
    public sealed class WebPartCodeGeneratorResult
    {
        /// <summary>
        /// Web part markup
        /// </summary>
        public string Markup { get; }


        /// <summary>
        /// Web part code
        /// </summary>
        public string Code { get; }


        /// <summary>
        /// Web part designer 
        /// </summary>
        public string Designer { get; }


        /// <summary>
        /// Creates new instance of <see cref="WebPartCodeGeneratorResult" />.
        /// </summary>
        /// <param name="markup">Markup content</param>
        /// <param name="code">Code behind content</param>
        /// <param name="designer">Designer content</param>
        public WebPartCodeGeneratorResult(string markup, string code, string designer)
        {
            Markup = markup;
            Code = code;
            Designer = designer;
        }
    }
}
