using System.Data;

using CMS;
using CMS.DataEngine;
using CMS.Scheduler;

[assembly: RegisterObjectType(typeof(SystemTaskListInfo), "cms.systemscheduledtasklist")]

namespace CMS.Scheduler
{
    /// <summary>
    /// List info for scheduled tasks generated by the system.
    /// </summary>
    public class SystemTaskListInfo : AbstractInfo<SystemTaskListInfo>
    {
        #region "Type information"

        /// <summary>
        /// Object type
        /// </summary>
        public const string OBJECT_TYPE = "cms.systemscheduledtasklist";


        /// <summary>
        /// Type information.
        /// </summary>
        public static ObjectTypeInfo TYPEINFO = GetTypeInfo();

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor - Creates an empty SystemTaskListInfo object.
        /// </summary>
        public SystemTaskListInfo()
            : base(TYPEINFO)
        {
        }


        /// <summary>
        /// Constructor - Creates a new SystemTaskListInfo object from the given DataRow.
        /// </summary>
        /// <param name="dr">DataRow with the object data</param>
        public SystemTaskListInfo(DataRow dr)
            : base(TYPEINFO, dr)
        {
        }

        #endregion


        #region "Methods"

        private static ObjectTypeInfo GetTypeInfo()
        {
            var typeInfo = ObjectTypeInfo.CreateListingObjectTypeInfo(OBJECT_TYPE, TaskInfo.TYPEINFO);
            typeInfo.TypeCondition = new TypeCondition().WhereEquals("TaskType", (int)ScheduledTaskTypeEnum.System);

            return typeInfo;
        }

        #endregion
    }
}
