//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WTE.Communication.CommunicationWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CommunicationAppWebServiceSoap", Namespace="http://www.WorldTradeEnterprise.com/webservices")]
    public partial class CommunicationAppWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private ServiceAuthHeader serviceAuthHeaderValueField;
        
        private System.Threading.SendOrPostCallback HealthCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailWithAttachmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendFaxMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendFormattedFaxMessageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CommunicationAppWebService() {
            this.Url = global::WTE.Communication.Properties.Settings.Default.WTE_Communication_CommunicationWebReference_CommunicationAppWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public ServiceAuthHeader ServiceAuthHeaderValue {
            get {
                return this.serviceAuthHeaderValueField;
            }
            set {
                this.serviceAuthHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HealthCheckCompletedEventHandler HealthCheckCompleted;
        
        /// <remarks/>
        public event SendEmailCompletedEventHandler SendEmailCompleted;
        
        /// <remarks/>
        public event SendEmailWithAttachmentCompletedEventHandler SendEmailWithAttachmentCompleted;
        
        /// <remarks/>
        public event SendSMSMessageCompletedEventHandler SendSMSMessageCompleted;
        
        /// <remarks/>
        public event SendFaxMessageCompletedEventHandler SendFaxMessageCompleted;
        
        /// <remarks/>
        public event SendFormattedFaxMessageCompletedEventHandler SendFormattedFaxMessageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ServiceAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.WorldTradeEnterprise.com/webservices/HealthCheck", RequestNamespace="http://www.WorldTradeEnterprise.com/webservices", ResponseNamespace="http://www.WorldTradeEnterprise.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInformation HealthCheck() {
            object[] results = this.Invoke("HealthCheck", new object[0]);
            return ((ResponseInformation)(results[0]));
        }
        
        /// <remarks/>
        public void HealthCheckAsync() {
            this.HealthCheckAsync(null);
        }
        
        /// <remarks/>
        public void HealthCheckAsync(object userState) {
            if ((this.HealthCheckOperationCompleted == null)) {
                this.HealthCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHealthCheckOperationCompleted);
            }
            this.InvokeAsync("HealthCheck", new object[0], this.HealthCheckOperationCompleted, userState);
        }
        
        private void OnHealthCheckOperationCompleted(object arg) {
            if ((this.HealthCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HealthCheckCompleted(this, new HealthCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ServiceAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.WorldTradeEnterprise.com/webservices/SendEmail", RequestNamespace="http://www.WorldTradeEnterprise.com/webservices", ResponseNamespace="http://www.WorldTradeEnterprise.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInformation SendEmail([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] Address[] toAddresses, Address fromAddress, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] Address[] ccAddresses, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] Address[] bccAddresses, string emailSubject, string emailBody, bool isHTMLBody) {
            object[] results = this.Invoke("SendEmail", new object[] {
                        toAddresses,
                        fromAddress,
                        ccAddresses,
                        bccAddresses,
                        emailSubject,
                        emailBody,
                        isHTMLBody});
            return ((ResponseInformation)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailAsync(Address[] toAddresses, Address fromAddress, Address[] ccAddresses, Address[] bccAddresses, string emailSubject, string emailBody, bool isHTMLBody) {
            this.SendEmailAsync(toAddresses, fromAddress, ccAddresses, bccAddresses, emailSubject, emailBody, isHTMLBody, null);
        }
        
        /// <remarks/>
        public void SendEmailAsync(Address[] toAddresses, Address fromAddress, Address[] ccAddresses, Address[] bccAddresses, string emailSubject, string emailBody, bool isHTMLBody, object userState) {
            if ((this.SendEmailOperationCompleted == null)) {
                this.SendEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailOperationCompleted);
            }
            this.InvokeAsync("SendEmail", new object[] {
                        toAddresses,
                        fromAddress,
                        ccAddresses,
                        bccAddresses,
                        emailSubject,
                        emailBody,
                        isHTMLBody}, this.SendEmailOperationCompleted, userState);
        }
        
        private void OnSendEmailOperationCompleted(object arg) {
            if ((this.SendEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailCompleted(this, new SendEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ServiceAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.WorldTradeEnterprise.com/webservices/SendEmailWithAttachment", RequestNamespace="http://www.WorldTradeEnterprise.com/webservices", ResponseNamespace="http://www.WorldTradeEnterprise.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInformation SendEmailWithAttachment(Addresses addresses, string emailSubject, string emailBody, bool isHTMLBody, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] AttachmentType[] attachments) {
            object[] results = this.Invoke("SendEmailWithAttachment", new object[] {
                        addresses,
                        emailSubject,
                        emailBody,
                        isHTMLBody,
                        attachments});
            return ((ResponseInformation)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailWithAttachmentAsync(Addresses addresses, string emailSubject, string emailBody, bool isHTMLBody, AttachmentType[] attachments) {
            this.SendEmailWithAttachmentAsync(addresses, emailSubject, emailBody, isHTMLBody, attachments, null);
        }
        
        /// <remarks/>
        public void SendEmailWithAttachmentAsync(Addresses addresses, string emailSubject, string emailBody, bool isHTMLBody, AttachmentType[] attachments, object userState) {
            if ((this.SendEmailWithAttachmentOperationCompleted == null)) {
                this.SendEmailWithAttachmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailWithAttachmentOperationCompleted);
            }
            this.InvokeAsync("SendEmailWithAttachment", new object[] {
                        addresses,
                        emailSubject,
                        emailBody,
                        isHTMLBody,
                        attachments}, this.SendEmailWithAttachmentOperationCompleted, userState);
        }
        
        private void OnSendEmailWithAttachmentOperationCompleted(object arg) {
            if ((this.SendEmailWithAttachmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailWithAttachmentCompleted(this, new SendEmailWithAttachmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ServiceAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.WorldTradeEnterprise.com/webservices/SendSMSMessage", RequestNamespace="http://www.WorldTradeEnterprise.com/webservices", ResponseNamespace="http://www.WorldTradeEnterprise.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInformation SendSMSMessage(string ToPhoneNumber, string SMSMessage) {
            object[] results = this.Invoke("SendSMSMessage", new object[] {
                        ToPhoneNumber,
                        SMSMessage});
            return ((ResponseInformation)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSMessageAsync(string ToPhoneNumber, string SMSMessage) {
            this.SendSMSMessageAsync(ToPhoneNumber, SMSMessage, null);
        }
        
        /// <remarks/>
        public void SendSMSMessageAsync(string ToPhoneNumber, string SMSMessage, object userState) {
            if ((this.SendSMSMessageOperationCompleted == null)) {
                this.SendSMSMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSMessageOperationCompleted);
            }
            this.InvokeAsync("SendSMSMessage", new object[] {
                        ToPhoneNumber,
                        SMSMessage}, this.SendSMSMessageOperationCompleted, userState);
        }
        
        private void OnSendSMSMessageOperationCompleted(object arg) {
            if ((this.SendSMSMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSMessageCompleted(this, new SendSMSMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ServiceAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.WorldTradeEnterprise.com/webservices/SendFaxMessage", RequestNamespace="http://www.WorldTradeEnterprise.com/webservices", ResponseNamespace="http://www.WorldTradeEnterprise.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInformation SendFaxMessage(string FaxNumber, string FaxFromName, string FaxMessage) {
            object[] results = this.Invoke("SendFaxMessage", new object[] {
                        FaxNumber,
                        FaxFromName,
                        FaxMessage});
            return ((ResponseInformation)(results[0]));
        }
        
        /// <remarks/>
        public void SendFaxMessageAsync(string FaxNumber, string FaxFromName, string FaxMessage) {
            this.SendFaxMessageAsync(FaxNumber, FaxFromName, FaxMessage, null);
        }
        
        /// <remarks/>
        public void SendFaxMessageAsync(string FaxNumber, string FaxFromName, string FaxMessage, object userState) {
            if ((this.SendFaxMessageOperationCompleted == null)) {
                this.SendFaxMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFaxMessageOperationCompleted);
            }
            this.InvokeAsync("SendFaxMessage", new object[] {
                        FaxNumber,
                        FaxFromName,
                        FaxMessage}, this.SendFaxMessageOperationCompleted, userState);
        }
        
        private void OnSendFaxMessageOperationCompleted(object arg) {
            if ((this.SendFaxMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendFaxMessageCompleted(this, new SendFaxMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ServiceAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.WorldTradeEnterprise.com/webservices/SendFormattedFaxMessage", RequestNamespace="http://www.WorldTradeEnterprise.com/webservices", ResponseNamespace="http://www.WorldTradeEnterprise.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInformation SendFormattedFaxMessage(string FaxNumber, string FaxFromName, string FaxMessage, string FaxFormat) {
            object[] results = this.Invoke("SendFormattedFaxMessage", new object[] {
                        FaxNumber,
                        FaxFromName,
                        FaxMessage,
                        FaxFormat});
            return ((ResponseInformation)(results[0]));
        }
        
        /// <remarks/>
        public void SendFormattedFaxMessageAsync(string FaxNumber, string FaxFromName, string FaxMessage, string FaxFormat) {
            this.SendFormattedFaxMessageAsync(FaxNumber, FaxFromName, FaxMessage, FaxFormat, null);
        }
        
        /// <remarks/>
        public void SendFormattedFaxMessageAsync(string FaxNumber, string FaxFromName, string FaxMessage, string FaxFormat, object userState) {
            if ((this.SendFormattedFaxMessageOperationCompleted == null)) {
                this.SendFormattedFaxMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFormattedFaxMessageOperationCompleted);
            }
            this.InvokeAsync("SendFormattedFaxMessage", new object[] {
                        FaxNumber,
                        FaxFromName,
                        FaxMessage,
                        FaxFormat}, this.SendFormattedFaxMessageOperationCompleted, userState);
        }
        
        private void OnSendFormattedFaxMessageOperationCompleted(object arg) {
            if ((this.SendFormattedFaxMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendFormattedFaxMessageCompleted(this, new SendFormattedFaxMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.WorldTradeEnterprise.com/webservices")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.WorldTradeEnterprise.com/webservices", IsNullable=false)]
    public partial class ServiceAuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.WorldTradeEnterprise.com/webservices")]
    public partial class AttachmentType {
        
        private string filenameField;
        
        private string nameField;
        
        private byte[] dataField;
        
        private int encodingField;
        
        private int mimeFlagsField;
        
        /// <remarks/>
        public string Filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public int Encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        public int MimeFlags {
            get {
                return this.mimeFlagsField;
            }
            set {
                this.mimeFlagsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.WorldTradeEnterprise.com/webservices")]
    public partial class Addresses {
        
        private Address fromAddressField;
        
        private Address[] toAddressesField;
        
        private Address[] cCAddressesField;
        
        private Address[] bCCAddressesField;
        
        private Address replyToAddressField;
        
        /// <remarks/>
        public Address FromAddress {
            get {
                return this.fromAddressField;
            }
            set {
                this.fromAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Address[] ToAddresses {
            get {
                return this.toAddressesField;
            }
            set {
                this.toAddressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Address[] CCAddresses {
            get {
                return this.cCAddressesField;
            }
            set {
                this.cCAddressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Address[] BCCAddresses {
            get {
                return this.bCCAddressesField;
            }
            set {
                this.bCCAddressesField = value;
            }
        }
        
        /// <remarks/>
        public Address ReplyToAddress {
            get {
                return this.replyToAddressField;
            }
            set {
                this.replyToAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.WorldTradeEnterprise.com/webservices")]
    public partial class Address {
        
        private string emailField;
        
        private string nameField;
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.WorldTradeEnterprise.com/webservices")]
    public partial class ResponseInformation {
        
        private int responseCodeField;
        
        private string responseMessageField;
        
        /// <remarks/>
        public int ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void HealthCheckCompletedEventHandler(object sender, HealthCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HealthCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HealthCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInformation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SendEmailCompletedEventHandler(object sender, SendEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInformation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SendEmailWithAttachmentCompletedEventHandler(object sender, SendEmailWithAttachmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailWithAttachmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailWithAttachmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInformation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SendSMSMessageCompletedEventHandler(object sender, SendSMSMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInformation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SendFaxMessageCompletedEventHandler(object sender, SendFaxMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendFaxMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendFaxMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInformation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SendFormattedFaxMessageCompletedEventHandler(object sender, SendFormattedFaxMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendFormattedFaxMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendFormattedFaxMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInformation)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591